---
  - name: Poweroff kubernetes workers
    hosts: localhost
    gather_facts: false
    connection: local
    become: true
    vars_files:
      - "roles/group_vars/all.yaml"
    roles:
     - role: roles/vcenter-poweroff-workers

  - name: Change scsi_bus_sharing in folders inside esxi
    hosts: esxi
    gather_facts: false
    become: true
    vars_files:
      - "roles/group_vars/all.yaml"
    roles:
     - role: roles/esxi-role-change-vmx

  - name: Poweron kubernetes workers
    hosts: localhost
    gather_facts: false
    connection: local
    become: true
    vars_files:
      - "roles/group_vars/all.yaml"
    roles:
     - role: roles/vcenter-poweron-workers
