  - name: Poweron all kubernetes workers
    vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "{{ item }}"
        state: powered-on
        validate_certs: no
    with_items:
          - "{{ worker1 }}"
          - "{{ worker2 }}"
          - "{{ worker3 }}"
    delegate_to: localhost
